### ISSUE TITLE
Let mariusmuntean/ChartJs.Blazor (no-longer-maintained) community know about this?

### ISSUE THREAD

**Issue by kchristman54** [erossini/BlazorChartjs#1]
While I haven't been able to compare the feature-set between this and the no-longer-maintained [mariusmuntean/ChartJs.Blazor](https://github.com/mariusmuntean/ChartJs.Blazor), I'm excited about there being an **actively** maintained ChartJs Blazor implementation. 

Would you like to contact that community (via their Issues) and let them know of your package? Or another option is to pull-in features from that or fork that. 

There's certainly interest:
https://github.com/mariusmuntean/ChartJs.Blazor/issues/199
https://github.com/mariusmuntean/ChartJs.Blazor/issues/191
https://github.com/mariusmuntean/ChartJs.Blazor/issues/160
https://github.com/mariusmuntean/ChartJs.Blazor/issues/179

Thanks for considering!

**Comment by erossini** [comment]
My implementation is different from the other repository. I won't spam that repo with mine but if you want to recommend my component. I'm happy 😉
