### ISSUE TITLE
"ChartHover" is spamming the console

### ISSUE THREAD

**Issue by TDroogers** [erossini/BlazorChartjs#11]
In Chart.razor you are spamming the console when you hover a chart.
I guess it is some test code that is left behind.

**Comment by erossini** [comment]
Yes, you are right. I'm removing the debug messages.

**Comment by erossini** [comment]
With the version [6.0.15](https://www.nuget.org/packages/PSC.Blazor.Components.Chartjs/6.0.15) this issue should be resolved. Please check and confirm.

Enrico

**Comment by TDroogers** [comment]
![afbeelding](https://user-images.githubusercontent.com/34547552/195780094-63833407-98bf-48b1-bb7b-d02edc7c60b2.png)

Sorry, I can't install this version.

**Comment by erossini** [comment]
OK, I think I found the issue. A new version is coming...

**Comment by erossini** [comment]
Version 6.0.16 is deployed. Please check and confirm.

**Comment by TDroogers** [comment]
Yes, it works
