### ISSUE TITLE
Bar chart mouse over the bar is black

### ISSUE THREAD

**Issue by erossini-chi** [erossini/BlazorChartjs#18]
I have an issue with the bar color when the mouse is over a bar. This is the example and how the bars are displaying at the beginning.

![image](https://user-images.githubusercontent.com/70210793/196899464-c7516305-b7d8-4e10-8153-b723464bd040.png)

When the mouse goes over a bar, the bar becomes black first

![image](https://user-images.githubusercontent.com/70210793/196899154-27920ef8-ff60-417a-86a2-5d137f9688a5.png)

and then, after few seconds, the bar has the expected colour.

![image](https://user-images.githubusercontent.com/70210793/196899249-c29ea7bf-c518-4463-a3c9-12f432637423.png)

How can I fix it?

Thank you,
Henry

**Comment by erossini** [comment]
Fixed it
