### ISSUE TITLE
Refresh Chart with new Data

### ISSUE THREAD

**Issue by MichaelCastano** [erossini/BlazorChartjs#2]
Hey
I just stumbled upon your project and tried it out in my Blazor Webassembly Project.
Works pretty well on first load until the point, when I fetched new Data from an Api and tried to refresh the Chart.

Maybe I am just missing something or this is not implemented yet.
I tried removing and adding a new Config with the new Data, but nothing happens.

In the main ChartJS Project you can just call `chart.update();` but did not found something similar here.

Is there a simple solution to refresh the Chart through your Wrapper Library?

Best regards
Michael

**Comment by erossini** [comment]
Hey,
I have my projects where I change data from API very often like yours. The only thing you have to do is to set a new configuration. 

```
<Chart Config="_config1" @ref="_chart1" Height="350px"></Chart>

@code {
    private string Id1 = "chart1";
    private BarChartConfig _config1;
    private Chart _chart1;

    public async Task RefreshDataAttributes(string filter)
    {
        dataAttribute = await _service.GetAttributeAsync(filter);
        if (!dataAttribute.Success)
        {
            _config1 = new BarChartConfig();
            InError = true;
            return;
        }

        _config1 = new BarChartConfig()
            {
                Type = ChartType.Bar,
                Options = new Options
                {
                    Plugins = new Plugins()
                    {
                        Legend = new Legend()
                        {
                            Align = LegendAlign.Center,
                            Display = false,
                            Position = LegendPosition.Right
                        }
                    },
                    Scales = new Scales()
                    {
                        X = new XAxes()
                        {
                            Stacked = true,
                            Ticks = new Ticks()
                            {
                                MaxRotation = 0,
                                MinRotation = 0
                            },
                            Title = new AxesTitle()
                            {
                                Display = true,
                                Text = "Importance score out of 100"
                            }
                        },
                        Y = new YAxes()
                        {
                            Stacked = true
                        }
                    },
                    IndexAxis = Axes.Y
                }
            };

        _config1.Data.Labels = dataAttribute.Dataset.Select(l => l.Attribute).ToList();
        _config1.Data.Datasets.Add(new BarDataset()
            {
                Label = "Value",
                BackgroundColor = ChartColors.Palette1,
                Data = dataAttribute.Dataset.Select(l => l.Value).ToList(),
                HoverBackgroundColor = ChartColors.Palette1
            });
    }
}
```

So, when you pass the new configuration, the JavaScript creates a new instance of the ChartJs.

If you see this [example](https://chartjs.puresourcecode.com/barSimple), it is working in the same way.

**Comment by erossini** [comment]
I'm going to close this issue. Let me know if you are ok with this code.

**Comment by jvmdc** [comment]
Recreating the chart for every config change means every time a change happens, the data will "bounce" into place, see this for an example: https://jsbin.com/juqomedona/1/edit?html,js,output

Contrast with this one, using the update() method in Chartjs: https://jsbin.com/wowitipome/1/edit?html,js,output - Notice how only the newest data point "bounces" into place.

**Comment by erossini** [comment]
Ok, I have to debug properly and in a stable Visual Studio (I'm using Visual Studio 2022 Preview).
