### ISSUE TITLE
Question: Pie chart options?

### ISSUE THREAD

**Issue by gerfen** [erossini/BlazorChartjs#27]
I'd like to create pie charts which have an arc of 180 degrees.  Is it possible to set circumference and rotation options?  For example, in pure JavaScript I would do this:

```
var chart = new Chart(canvas, {
  type: 'doughnut',
  data: ['400', '200'],
  options: {
    rotation: -90,
    circumference: 180,
}
```

**Comment by erossini** [comment]
The package [PSC.Blazor.Components.Chartjs 6.0.30](https://www.nuget.org/packages/PSC.Blazor.Components.Chartjs/6.0.30) was recently published on NuGet Gallery by erossini.

**Comment by gerfen** [comment]
@erossini Thank you!
