### ISSUE TITLE
Show value on Line And Bar graph ?

### ISSUE THREAD

**Issue by hagaygo** [erossini/BlazorChartjs#33]
Hi,

I am testing this component with line and bar graph.

At the moment i am missing the option to show the value on the graph it self.

I see it is supported by ChartJS (using plugin) is it somehow possible with this component ?

I would appreciate any pointers,

Thanks in advance.

**Comment by erossini** [comment]
Hi,
I'm adding this option in the next release of the component.

**Comment by erossini** [comment]
Hey! I have just release a new version of the component and I added a way to add labels to the chart. You have an example [here](https://chartjs.puresourcecode.com/lineLabels). More info on [PureSorceCode.com](https://www.puresourcecode.com/dotnet/blazor/labels-and-onclickchart-for-chartjs/)

Please let me know if it is working.

**Comment by hagaygo** [comment]
Thanks , seems to be working.

FYI : After updating the nuget package my app had an error when trying to show the graphs.

Error: Microsoft.JSInterop.JSException: ChartDataLabels is not defined

Only after adding the following lines to my app : 

<script src="_content/PSC.Blazor.Components.Chartjs/lib/chartjs-plugin-zoom/chartjs-plugin-zoom.js"></script>
<script src="_content/PSC.Blazor.Components.Chartjs/lib/chartjs-plugin-datalabels/chartjs-plugin-datalabels.js"></script>

The graph were shown again.

Not sure this is your intended behavior.

**Comment by erossini** [comment]
`ChartDataLabels` is coming from the `chartjs-plugin-datalabels`. In my test I haven't received this error also when the library wasn't there.

I'm fixing now this bug.

**Comment by erossini** [comment]
With the new version of the component, you should don't have any issue. Could you update the component in your project and try again please?

**Comment by hagaygo** [comment]
I can confirm that after updating to 6.0.38, the graphs are shown (and no errors of course) even without adding 

```
<script src="_content/PSC.Blazor.Components.Chartjs/lib/chartjs-plugin-zoom/chartjs-plugin-zoom.js"></script>
<script src="_content/PSC.Blazor.Components.Chartjs/lib/chartjs-plugin-datalabels/chartjs-plugin-datalabels.js"></script>
```

Thanks for the quick fix.
