### ISSUE TITLE
Tooltip Title CallBack

### ISSUE THREAD

**Issue by gmlloves** [erossini/BlazorChartjs#36]
Hello :)

Can you implement the Title Callback?
  
```
Tooltip = new Tooltip()
{
    Callbacks = new Callbacks()
    {
        Title = (ctx) => XXXX,    <--- add this functionality
        Label = (ctx) => null
    }                   
}
```

Thank you in advance

**Comment by gmlloves** [comment]
Hello,

I like to set the tooltip title (and remove the label) because the bars on my chart are not tall and are hidden by the tooltip.
Chartjs's config in javascript:

```
callback: {
title:  function(context) { return context[0].label + context[0].formattedValue },
label: function(context) { return ""; }
}
```

Thank you

**Comment by erossini** [comment]
I added a callbacks for `Title` and `Labels`. You can see the demo page [here](https://chartjs.puresourcecode.com/callback)
I'll release the NuGet package tomorrow

**Comment by erossini** [comment]
Is it working? Can I close the issue?

**Comment by gmlloves** [comment]
Yes, it is working! :)
Thank you, Gaston
