### ISSUE TITLE
SyntaxError - Chart.js:46

### ISSUE THREAD

**Issue by gmlloves** [erossini/BlazorChartjs#40]
Hello, 

I get this error on startup: Uncaught SyntaxError: export declarations may only appear at top level of a module Chart.js:46
Can you see it?

Thank you,
Gaston.

**Comment by erossini** [comment]
Yes, I saw this message. It is related to this [line](https://github.com/erossini/BlazorChartjs/blob/6d038d8ca44f370042fb7611b601214d31cb2f30/src/wwwroot/Chart.js#L46) where there is the word `export function`. If I remove the `export` the script is not working.

I don't know why this is a syntax error.

**Comment by gmlloves** [comment]
It happens because the export directive is for modules and not for plain Javascript.

> Add at the end of the page the following scripts:
```
<script src="_content/PSC.Blazor.Components.Chartjs/lib/Chart.js/chart.js"></script>
<script src="_content/PSC.Blazor.Components.Chartjs/Chart.js"></script>
```

The <script src="_content/PSC.Blazor.Components.Chartjs/Chart.js"></script> is not neccesary because it is imported from:

 ```
      public ChartJsInterop(IJSRuntime jsRuntime)
        {
            moduleTask = new(() => jsRuntime.InvokeAsync<IJSObjectReference>("import",
                "./_content/PSC.Blazor.Components.Chartjs/Chart.js").AsTask());
        }
```

I removed it from my index.html and the error does not happen anymore.

**Comment by erossini** [comment]
Thank you so much!

**Comment by Ryan-ECPPro** [comment]
Hi,

We are still seeing the same error on line 46 using version:
<PackageReference Include="PSC.Blazor.Components.Chartjs" Version="6.0.40" />

Was @gmlloves suggestion above incorporated in a later release or I am missing something in the suggested change.

Thanks

**Comment by skotl** [comment]
Confirm this issue still exists, albeit it displays as `Uncaught SyntaxError: Unexpected token 'export' (at Chart.js:46:1)`

Removing the second `script src=...` from index.html, as described by @gmlloves above, addresses it.

Not sure whether this issue can be reopened?

**Comment by Ryan-ECPPro** [comment]
Hi,

I can confirm removing the second line works perfectly.

Thank you @skotl, and thank you @erossini for providing the wrapper!!

**Comment by erossini** [comment]
Thank you @skotl and @Ryan-ECPPro 
I'm working on a new version of the components with more functionalities. Hopefully soon, few improvements.

**Comment by grofit** [comment]
I have tried removing the 2nd line but for some reason the first time it loads it always seems to fail then when I refresh it works as expected.

Either way I am not sure if this bug should be classed as closed as its not fixed in the latest release and requires a manual workaround, are you able to issue a hotfix for this and do a larger release with all your other changes further down the line?
