### ISSUE TITLE
Line and Labels

### ISSUE THREAD

**Issue by Hamsavani-J** [erossini/BlazorChartjs#44]
I have checked the line and labels chart, and I tried it but on the webpage, it shows a line with labels like 65, 59, 91, etc. 
But when I tried with the code you have given in linesimplelabel.razor, It doesn't show any label.
I'm getting lines without labels like this:

![Screenshot 2023-05-08 192108](https://user-images.githubusercontent.com/68469382/236843895-3db8779a-c38a-489f-8bf7-9565a63a8349.png)

Is the code you have given correct, does it show the lines with the label, or do have to do anything else to get the labels?

 Please let me know  @erossini

**Comment by erossini** [comment]
Did you add the script `chartjs-plugin-datalabels` in your `index.htm`?

**Comment by Hamsavani-J** [comment]
I didn't add that one. Sorry and Thank you so much.
