### ISSUE TITLE
GPL License

### ISSUE THREAD

**Issue by mahald** [erossini/BlazorChartjs#52]
This library is licensed under the GPL, which requires that any project utilizing it must disclose all of its source code, thereby prohibiting its use in commercial projects that do not intend to release their source code publicly. is that the intention?

**Comment by erossini** [comment]
No, the intention was to offer this library free for every use. If someone finds this library useful, I hope in funding or support.
I'll change the licence.

Enrico

**Comment by yxbh** [comment]
Would love to see this changed to MIT license.

**Comment by erossini** [comment]
Updated

**Comment by NotTsunami** [comment]
@erossini On NuGet, it still shows GPL.

https://www.nuget.org/packages/PSC.Blazor.Components.Chartjs/8.0.6/License

**Comment by NotTsunami** [comment]
Still needs to be updated on NuGet.
