### ISSUE TITLE
BeginAtZero not working

### ISSUE THREAD

**Issue by parko65** [erossini/BlazorChartjs#7]
Hi, you recently posted an article on https://www.puresourcecode.com/dotnet/blazor/using-chart-js-with-blazor/ explaining how to use Chart.js in Blazor.

After much testing I've found that the anonymous Options object is not being mapped to the JS config object. No matter what properties I put in the Options object, the changes are not reflected at runtime.

**Comment by erossini** [comment]
Can you give me an example? I'm using this component for a lot of different applications in production and I don't have issues.
