### ISSUE TITLE
Missing license attribution & potential endorsement/redirect

### ISSUE THREAD

**Issue by Joelius300** [erossini/BlazorChartjs#84]
Hey there, I'm Joel, co-author and ex-maintainer of [ChartJs.Blazor](https://github.com/mariusmuntean/ChartJs.Blazor).
First of all, thank you for maintaining this library and giving the users an alternative to our outdated one!

I was contacted in regard to a potential license violation, because it seems that this project is using code from ChartJs.Blazor without attribution of license and copyright. A very obvious case of that is [ColorUtil](https://github.com/erossini/BlazorChartjs/commit/dcd9c05eb6814a7f19bf28d675a582988d624415#diff-05fb52a38d3f4efed04ea9fd26faf3a6f7607100e737509e1e003327c75a82a5), which is a 1:1 copy of [ours](https://github.com/mariusmuntean/ChartJs.Blazor/blame/master/src/ChartJs.Blazor/Util/ColorUtil.cs) (apart from the namespace).

I am glad our project was able to inspire you and that our code helped you kickstart the project, but I am disappointed that you don't ever mention it anywhere. Primarily, I would like to see it because we're all doing this in our free time and out of passion, so showing appreciation for the work of others that you are building on is in my opinion much needed to sustain a friendly open source community. Additionally, from a legal perspective, not attributing is in violation of the MIT license, which states:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

Could you please add appropriate attribution to your readme?

The correct attribution for your license file would be the following IIRC. For the readme I'm sure you can come up with something fitting.

```
Copyright (c) 2019 Marius Muntean
Copyright (c) 2021 Joel L.
Copyright (c) 2024 Enrico Rossini
```

Aside from this, I think it might be a good idea to point users of our library to yours. If you are interested, I can arrange that after the attribution issue is fixed.

Thanks in advance. If you have any questions let me know :)

Kind regards,
Joel

**Comment by erossini** [comment]
Hi @Joelius300,
I hope you are well. I'm sorry if the class ColorUtil is your code without attribution. A few years ago, I found this code somewhere on Stackoverflow. I'll add the attribution to you for this class.

Thank you in advance,
Enrico

**Comment by Joelius300** [comment]
Interesting, I couldn't find anything. Are you claiming that you built this library without using ours as reference? 
No offense, but I'm finding that hard to believe. There are more examples of copied code, like [IDataset](https://github.com/erossini/BlazorChartjs/blob/main/src/Interfaces/IDataset.cs) (and [our version](https://github.com/mariusmuntean/ChartJs.Blazor/blob/master/src/ChartJs.Blazor/Common/IDataset.cs)). Not sure if you're even using that code, but I would be surprised to hear that you didn't copy anything from us..

I am not at all upset that you used code from us, quite the opposite, I am actively encouraging you to built upon our project! If we didn't want that, we wouldn't have licensed it under MIT. Also it's great that there is an actively maintained library doing the thing our abandoned, outdated one did, I'm sure our users are very glad about that too. The only thing I would like to see is attribution for our work.

**Comment by erossini** [comment]
Hello!
Although I didn't copy your code on purpose, using what I found on Stackover or other sites, some classes are coming from your repo. So, I added a `Contribution` section in the `README` mentioning that.

Enrico

**Comment by Joelius300** [comment]
Okay, thank you. Would you mind changing it to "ChartJs.Blazor Contributors" or mentioning me personally? Not to discredit Marius, I'm very fond of his work, but I maintained the library from late 2019 to early 2021 without him. Also, the repo has been abandoned since my departure (except for one very brief return of Marius to merge a single PR).

**Comment by Joelius300** [comment]
@erossini please update the contributors.

**Comment by Joelius300** [comment]
I'm disappointed to see you choose this way, but I'll let it go now. \
FYI, changing the files further to obfuscate that you copied them does not remove the need to retain copyright and license notices. Apart from all the legal stuff, which I won't pursue, it's frustrating to see people avoiding even the simplest of acknowledgements of others' work, especially when everyone is doing it for free in their free time.
